baseURL = "https://blog.xumiao.link/"
title = "XuMiao's Blog"
copyright = "Finish"
languageCode = 'en'
defaultContentLanguage = "en"
hasCJKLanguage = true
enableInlineShortcodes = true

ignoreErrors = ["error-remote-getjson"]
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

[markup]
[markup.highlight]
  lineNos = false
  noClasses = true
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.cjk]
      enable = true
      eastAsianLineBreaks = true
      escapedSpace = true

[privacy]
  [privacy.vimeo]
    disabled = true
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.120.0"
