baseURL = 'https://blog.xumiao.link/'
title = "Happy everyday"
copyright = "begin"
pagination.pagerSize = 10
languageCode = "en"
theme = "tailwind"
buildDrafts = true
showAuthor = true
[markup]
  _merge = "deep"
[author]
  name = "xumiao"
  email = "1465498242@qq.com"

[params]
  contentTypeName = "posts"

  [params.header]
    logo = "logo.jpg"
    title = "xumiao"

  [params.footer]
    since = 2025
    poweredby = false

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"